epoch: 120
lr: 0.0001
batchsize: 32
trainsize: 256
decay_rate: 0.1
decay_epoch: 80
logdir: log/
input_path: ./data_aug/
save_path: results/

dataset_path: ./dataset/
model_path: ./results/SOLNet_convert.pth
testsize: 256