#Train
epoch: 120
lr: 0.0001
batchsize: 32
trainsize: 256
decay_rate: 0.1
step_size: 80
decay_epoch: 80
logdir: log/xxx/   #xxx ---> Name of experiment
image_root: ./dataset/data_aug/train/images/
gt_root: ./dataset/data_aug/train/GT/
save_path: ./results/xxx/weights/  #xxx ---> Name of experiment

#model convert
checkpoint: ./results/xxx/weights/SOLNet.pth.120
model_path: ./results/xxx/weight_convert/SOLNet_convert.pth
